---
title: "SCRIPT FOR DRAWING AND ANALYZING NETWORKS IN R"
output: html_notebook
---
Author: Julian Olaya Restrepo.
e-mail: jolaya@stanford.edu, julianolaya80@yahoo.com
Run in: R version 4.3.3 (2024-02-29 ucrt)

```{r}
library("bipartite")
library("ggplot2")
library("network")
library("png")
library("plyr")
library("reshape2")
library("rstudioapi")
library("permute")
library("dplyr")
library( "igraph" )
library( "RColorBrewer" )
```

Import nodes and edges
```{r}
nodes <- read.csv("Nodes.csv")
edges <- read.csv("Edges.csv")
```

Build graph from dataframe
```{r}
net_caulker <- graph_from_data_frame( d = edges, vertices = nodes, directed = FALSE )
```

Define colours for nodes based on type of interaction
```{r}
color_map <- c(
  "prearrangement" = "maroon",
  "Buy" = "deepskyblue",
  "Training" = "green",
  "Education" = "blue",
  "Research" = "orange",
  "Governance" = "chartreuse4",
  "Other" = "darkorchid",
  "Licensing" = "gold",
  "share" = "magenta",
  "Sell" = "red",
  "self_consumption" = "wheat4"
)

E(net_caulker)$color <- color_map[E(net_caulker)$Link.type]
```

Edge are aggregated by: "sum" (The sum of the attributes is calculated)

```{r}
net_caulker <- simplify(net_caulker, remove.loops = F,                                      edge.attr.comb=list(intencidade="sum","ignore"))
```












